// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"zero-backend/internal/config"
	"zero-backend/internal/storage/mongodb"
	"zero-backend/internal/storage/redis"
	"zero-backend/modules/worker/handler"
	"zero-backend/modules/worker/server"
	"zero-backend/pkg/queue"
	"zero-backend/providers"
)

// Injectors from wire.go:

func wireApp() *server.WorkerServer {
	configConfig := config.New()
	client := redis.New(configConfig)
	queueManager := queue.NewQueueManager(client)
	conn := mongodb.NewConn(configConfig)
	database := conn.DB
	logger := providers.ProvideLogger(configConfig, database)
	exampleHandler := handler.NewExampleHandler(logger)
	registry := providers.ProvideRegistry(logger, exampleHandler)
	workerServer := server.NewWorkerServer(queueManager, registry, logger)
	return workerServer
}
