// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"zero-backend/internal/config"
	"zero-backend/modules/worker/handler"
	"zero-backend/modules/worker/server"
	"zero-backend/pkg/mongodb"
	"zero-backend/pkg/queue"
	"zero-backend/pkg/redis"
	"zero-backend/providers"
)

// Injectors from wire.go:

func wireApp() *server.WorkerServer {
	configConfig := config.New()
	redisConfig := providers.NewRedisConfig(configConfig)
	client := redis.New(redisConfig)
	queueManager := queue.NewQueueManager(client)
	mongodbConfig := providers.NewMongoDBConfig(configConfig)
	conn := mongodb.NewConn(mongodbConfig)
	database := conn.DB
	zeroLogger := providers.ProvideLogger(configConfig, database)
	exampleHandler := handler.NewExampleHandler(zeroLogger)
	registry := providers.ProvideRegistry(zeroLogger, exampleHandler)
	workerServer := server.NewWorkerServer(queueManager, registry, zeroLogger)
	return workerServer
}
