// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/241x/zero-kit/mongodb"
	"github.com/241x/zero-kit/queue"
	"github.com/241x/zero-kit/redis"
	"zero-backend/cmd/worker/handler"
	"zero-backend/cmd/worker/server"
	"zero-backend/internal/config"
	"zero-backend/providers"
)

// Injectors from wire.go:

func wireApp() (*server.WorkerServer, error) {
	configConfig := config.New()
	redisConfig := providers.NewRedisConfig(configConfig)
	client := redis.New(redisConfig)
	queueManager := queue.NewQueueManager(client)
	loggerConfig := configConfig.Logger
	mongodbConfig := providers.NewMongoDBConfig(configConfig)
	conn, err := mongodb.NewConn(mongodbConfig)
	if err != nil {
		return nil, err
	}
	database := conn.DB
	zeroLogger := providers.ProvideLogger(loggerConfig, database)
	exampleHandler := handler.NewExampleHandler(zeroLogger)
	registry := providers.ProvideRegistry(zeroLogger, exampleHandler)
	workerServer := server.NewWorkerServer(queueManager, registry, zeroLogger)
	return workerServer, nil
}
