// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/241x/zero-kit/mongodb"
	"github.com/241x/zero-kit/mysql"
	"github.com/241x/zero-kit/redis"
	"zero-backend/internal/config"
	"zero-backend/internal/middleware"
	"zero-backend/internal/repository"
	"zero-backend/internal/request"
	service2 "zero-backend/internal/service"
	"zero-backend/modules/api/controller"
	middleware2 "zero-backend/modules/api/middleware"
	"zero-backend/modules/api/server"
	"zero-backend/modules/api/service"
	"zero-backend/providers"
)

// Injectors from wire.go:

func wireApp() (*server.HTTPServer, error) {
	configConfig := config.New()
	serverConfig := providers.NewApiServerConfig(configConfig)
	validate := request.NewValidate()
	translator := request.NewTrans(validate)
	requestRequest := request.NewRequest(validate, translator)
	mysqlConfig := providers.NewMySQLConfig(configConfig)
	loggerConfig := configConfig.Logger
	mongodbConfig := providers.NewMongoDBConfig(configConfig)
	conn, err := mongodb.NewConn(mongodbConfig)
	if err != nil {
		return nil, err
	}
	database := conn.DB
	zeroLogger := providers.ProvideLogger(loggerConfig, database)
	logger := mysql.NewLogger(zeroLogger)
	db, err := mysql.NewDB(mysqlConfig, logger)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(db)
	apiAuthConfig := providers.NewApiAuthConfig(configConfig)
	redisConfig := providers.NewRedisConfig(configConfig)
	client := redis.New(redisConfig)
	authService := service.NewAuthService(userRepository, apiAuthConfig, client)
	authController := controller.NewAuthController(requestRequest, authService, apiAuthConfig)
	uploadFileRepository := repository.NewUploadFileRepository(db)
	settingRepository := repository.NewSettingRepository(db)
	settingDefaultRepository := repository.NewSettingDefaultRepository(db)
	settingService := service2.NewSettingService(settingRepository, settingDefaultRepository)
	uploadFileService := service2.NewUploadFileService(uploadFileRepository, settingService)
	uploadFileController := controller.NewUploadFileController(requestRequest, uploadFileService)
	regionRepository := repository.NewRegionRepository(db)
	regionService := service2.NewRegionService(regionRepository, settingService)
	regionController := controller.NewRegionController(regionService)
	settingController := controller.NewSettingController(settingService)
	controllers := &controller.Controllers{
		AuthController:       authController,
		UploadFileController: uploadFileController,
		RegionController:     regionController,
		SettingController:    settingController,
	}
	beforeMiddleware := middleware.NewBeforeMiddleware(zeroLogger)
	middlewares := &middleware.Middlewares{
		Before: beforeMiddleware,
	}
	authMiddleware := middleware2.NewAuthMiddleware(apiAuthConfig, authService)
	middlewareMiddlewares := &middleware2.Middlewares{
		Auth: authMiddleware,
	}
	corsConfig := providers.NewApiCorsConfig(configConfig)
	engine := server.NewGin(controllers, middlewares, middlewareMiddlewares, corsConfig)
	httpServer := server.NewHTTPServer(serverConfig, engine, zeroLogger)
	return httpServer, nil
}
