// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"zero-backend/internal/config"
	"zero-backend/internal/middleware"
	"zero-backend/internal/repository"
	"zero-backend/internal/request"
	service2 "zero-backend/internal/service"
	"zero-backend/internal/storage/mongodb"
	"zero-backend/internal/storage/mysql"
	"zero-backend/internal/storage/redis"
	"zero-backend/modules/api/controller"
	middleware2 "zero-backend/modules/api/middleware"
	"zero-backend/modules/api/server"
	"zero-backend/modules/api/service"
	"zero-backend/providers"
)

// Injectors from wire.go:

func wireApp() *server.HTTPServer {
	configConfig := config.New()
	validate := request.NewValidate()
	translator := request.NewTrans(validate)
	requestRequest := request.NewRequest(validate, translator)
	conn := mongodb.NewConn(configConfig)
	database := conn.DB
	logger := providers.ProvideLogger(configConfig, database)
	mysqlLogger := mysql.NewLogger(logger)
	db := mysql.NewDB(configConfig, mysqlLogger)
	userRepository := repository.NewUserRepository(db)
	client := redis.New(configConfig)
	authService := service.NewAuthService(userRepository, configConfig, client)
	authController := controller.NewAuthController(requestRequest, authService, configConfig)
	uploadFileRepository := repository.NewUploadFileRepository(db)
	settingRepository := repository.NewSettingRepository(db)
	settingDefaultRepository := repository.NewSettingDefaultRepository(db)
	settingService := service2.NewSettingService(settingRepository, settingDefaultRepository)
	uploadFileService := service2.NewUploadFileService(uploadFileRepository, settingService)
	uploadFileController := controller.NewUploadFileController(requestRequest, uploadFileService)
	regionRepository := repository.NewRegionRepository(db)
	regionService := service2.NewRegionService(regionRepository, settingService)
	regionController := controller.NewRegionController(regionService)
	settingController := controller.NewSettingController(settingService)
	controllers := &controller.Controllers{
		AuthController:       authController,
		UploadFileController: uploadFileController,
		RegionController:     regionController,
		SettingController:    settingController,
	}
	beforeMiddleware := middleware.NewBeforeMiddleware(logger)
	corsMiddleware := middleware.NewCorsMiddleware(configConfig)
	middlewares := &middleware.Middlewares{
		Before: beforeMiddleware,
		Cors:   corsMiddleware,
	}
	authMiddleware := middleware2.NewAuthMiddleware(configConfig, authService)
	middlewareMiddlewares := &middleware2.Middlewares{
		Auth: authMiddleware,
	}
	engine := server.NewGin(controllers, middlewares, middlewareMiddlewares)
	httpServer := server.NewHTTPServer(configConfig, engine, logger)
	return httpServer
}
