// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/241x/zero-kit/bind"
	"github.com/241x/zero-kit/gormutil"
	"github.com/241x/zero-kit/mongodb"
	"github.com/241x/zero-kit/mysql"
	"github.com/241x/zero-kit/redis"
	"github.com/241x/zero-web/server"
	"zero-backend/internal/config"
	"zero-backend/modules/admin/router"
	"zero-backend/providers"
)

// Injectors from wire.go:

func wireApp() (*server.Server, error) {
	configConfig := config.New()
	serverConfig := providers.NewAdminServerConfig(configConfig)
	loggerConfig := configConfig.Logger
	mongodbConfig := providers.NewMongoDBConfig(configConfig)
	conn, err := mongodb.NewConn(mongodbConfig)
	if err != nil {
		return nil, err
	}
	database := conn.DB
	zeroLogger := providers.ProvideLogger(loggerConfig, database)
	mysqlConfig := providers.NewMySQLConfig(configConfig)
	logger := gormutil.NewLogger(zeroLogger)
	db, err := mysql.NewDB(mysqlConfig, logger)
	if err != nil {
		return nil, err
	}
	validate := bind.NewValidate()
	translator, err := bind.NewTrans(validate)
	if err != nil {
		return nil, err
	}
	code := providers.ProvideBindErrCode()
	binder := bind.New(validate, translator, code)
	adminAuthConfig := providers.NewAdminAuthConfig(configConfig)
	corsConfig := providers.NewAdminCorsConfig(configConfig)
	service := providers.NewSettingService(db)
	redisConfig := providers.NewRedisConfig(configConfig)
	client := redis.New(redisConfig)
	captchaConfig := providers.NewCaptchaConfig(configConfig)
	captchaService := providers.NewCaptchaService(client, captchaConfig)
	engine := router.NewGin(zeroLogger, db, binder, adminAuthConfig, corsConfig, service, captchaService)
	v := providers.ProvideServerOptions()
	serverServer := server.New(serverConfig, engine, zeroLogger, v...)
	return serverServer, nil
}
