// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/241x/zero-kit/bind"
	"github.com/241x/zero-kit/gormutil"
	"github.com/241x/zero-kit/mongodb"
	"github.com/241x/zero-kit/mysql"
	"github.com/241x/zero-kit/redis"
	"github.com/241x/zero-web/middleware"
	"zero-backend/internal/config"
	"zero-backend/internal/repository"
	"zero-backend/internal/service"
	"zero-backend/modules/admin/controller"
	middleware2 "zero-backend/modules/admin/middleware"
	"zero-backend/modules/admin/server"
	service2 "zero-backend/modules/admin/service"
	"zero-backend/providers"
)

// Injectors from wire.go:

func wireApp() (*server.HTTPServer, error) {
	configConfig := config.New()
	serverConfig := providers.NewAdminServerConfig(configConfig)
	validate := bind.NewValidate()
	translator, err := bind.NewTrans(validate)
	if err != nil {
		return nil, err
	}
	code := providers.ProvideBindErrCode()
	binder := bind.New(validate, translator, code)
	mysqlConfig := providers.NewMySQLConfig(configConfig)
	loggerConfig := configConfig.Logger
	mongodbConfig := providers.NewMongoDBConfig(configConfig)
	conn, err := mongodb.NewConn(mongodbConfig)
	if err != nil {
		return nil, err
	}
	database := conn.DB
	zeroLogger := providers.ProvideLogger(loggerConfig, database)
	logger := gormutil.NewLogger(zeroLogger)
	db, err := mysql.NewDB(mysqlConfig, logger)
	if err != nil {
		return nil, err
	}
	rbacUserRepository := repository.NewRbacUserRepository(db)
	rbacApiRepository := repository.NewRbacApiRepository(db)
	rbacRoleRepository := repository.NewRbacRoleRepository(db)
	rbacMenuRepository := repository.NewRbacMenuRepository(db)
	rbacRoleMenuRepository := repository.NewRbacRoleMenuRepository(db)
	rbacUserRoleRepository := repository.NewRbacUserRoleRepository(db)
	rbacMenuApiRepository := repository.NewRbacMenuApiRepository(db)
	adminAuthConfig := providers.NewAdminAuthConfig(configConfig)
	redisConfig := providers.NewRedisConfig(configConfig)
	client := redis.New(redisConfig)
	captchaConfig := providers.NewCaptchaConfig(configConfig)
	captchaService := service.NewCaptchaService(client, captchaConfig)
	authService := service2.NewAuthService(rbacUserRepository, rbacApiRepository, rbacRoleRepository, rbacMenuRepository, rbacRoleMenuRepository, rbacUserRoleRepository, rbacMenuApiRepository, adminAuthConfig, client, captchaService)
	authController := controller.NewAuthController(binder, authService, adminAuthConfig)
	captchaController := controller.NewCaptchaController(binder, captchaService)
	rbacMenuService := service.NewRbacMenuService(rbacMenuRepository, rbacMenuApiRepository, db)
	rbacMenuController := controller.NewRbacMenuController(binder, rbacMenuService)
	rbacApiService := service.NewRbacApiService(rbacApiRepository)
	rbacApiController := controller.NewRbacApiController(binder, rbacApiService)
	rbacRoleService := service.NewRbacRoleService(rbacRoleRepository, rbacRoleMenuRepository, db)
	rbacRoleController := controller.NewRbacRoleController(rbacRoleService, binder)
	rbacUserService := service.NewRbacUserService(db, rbacUserRepository, rbacUserRoleRepository)
	rbacUserController := controller.NewRbacUserController(binder, rbacUserService)
	rbacStoreRepository := repository.NewRbacStoreRepository(db)
	rbacStoreService := service.NewRbacStoreService(rbacStoreRepository)
	rbacStoreController := controller.NewRbacStoreController(binder, rbacStoreService)
	uploadGroupRepository := repository.NewUploadGroupRepository(db)
	uploadGroupService := service.NewUploadGroupService(uploadGroupRepository)
	uploadGroupController := controller.NewUploadGroupController(binder, uploadGroupService)
	uploadFileRepository := repository.NewUploadFileRepository(db)
	settingRepository := repository.NewSettingRepository(db)
	settingDefaultRepository := repository.NewSettingDefaultRepository(db)
	settingService := service.NewSettingService(settingRepository, settingDefaultRepository)
	uploadFileService := service.NewUploadFileService(uploadFileRepository, settingService)
	uploadFileController := controller.NewUploadFileController(binder, uploadFileService)
	userRepository := repository.NewUserRepository(db)
	userPointsLogRepository := repository.NewUserPointsLogRepository(db)
	userService := service.NewUserService(db, userRepository, userPointsLogRepository)
	userController := controller.NewUserController(binder, userService)
	settingController := controller.NewSettingController(binder, settingService)
	settingDefaultService := service.NewSettingDefaultService(settingDefaultRepository)
	settingDefaultController := controller.NewSettingDefaultController(binder, settingDefaultService)
	articleCategoryRepository := repository.NewArticleCategoryRepository(db)
	articleCategoryService := service.NewArticleCategoryService(articleCategoryRepository)
	articleCategoryController := controller.NewArticleCategoryController(binder, articleCategoryService)
	articleRepository := repository.NewArticleRepository(db)
	articleService := service.NewArticleService(articleRepository)
	articleController := controller.NewArticleController(binder, articleService)
	regionRepository := repository.NewRegionRepository(db)
	regionService := service.NewRegionService(regionRepository, settingService)
	regionController := controller.NewRegionController(regionService)
	healthController := controller.NewHealthController()
	controllers := &controller.Controllers{
		AuthController:            authController,
		CaptchaController:         captchaController,
		RbacMenuController:        rbacMenuController,
		RbacApiController:         rbacApiController,
		RbacRoleController:        rbacRoleController,
		RbacUserController:        rbacUserController,
		RbacStoreController:       rbacStoreController,
		UploadGroupController:     uploadGroupController,
		UploadFileController:      uploadFileController,
		UserController:            userController,
		SettingController:         settingController,
		SettingDefaultController:  settingDefaultController,
		ArticleCategoryController: articleCategoryController,
		ArticleController:         articleController,
		RegionController:          regionController,
		HealthController:          healthController,
	}
	traceMiddleware := middleware.NewTraceMiddleware(zeroLogger)
	requestLogger := middleware.NewRequestLogger()
	middlewares := &middleware.Middlewares{
		Trace:         traceMiddleware,
		RequestLogger: requestLogger,
	}
	authMiddleware := middleware2.NewAuthMiddleware(adminAuthConfig, authService)
	middlewareMiddlewares := &middleware2.Middlewares{
		Auth: authMiddleware,
	}
	corsConfig := providers.NewAdminCorsConfig(configConfig)
	engine := server.NewGin(controllers, middlewares, middlewareMiddlewares, corsConfig)
	httpServer := server.NewHTTPServer(serverConfig, engine, zeroLogger, db)
	return httpServer, nil
}
