// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"zero-backend/internal/config"
	"zero-backend/internal/middleware"
	"zero-backend/internal/repository"
	"zero-backend/internal/request"
	service2 "zero-backend/internal/service"
	"zero-backend/modules/admin/controller"
	middleware2 "zero-backend/modules/admin/middleware"
	"zero-backend/modules/admin/server"
	"zero-backend/modules/admin/service"
	"zero-backend/pkg/mongodb"
	"zero-backend/pkg/mysql"
	"zero-backend/pkg/redis"
	"zero-backend/providers"
)

// Injectors from wire.go:

func wireApp() *server.HTTPServer {
	configConfig := config.New()
	serverConfig := providers.NewAdminServerConfig(configConfig)
	validate := request.NewValidate()
	translator := request.NewTrans(validate)
	requestRequest := request.NewRequest(validate, translator)
	mysqlConfig := providers.NewMySQLConfig(configConfig)
	loggerConfig := configConfig.Logger
	mongodbConfig := providers.NewMongoDBConfig(configConfig)
	conn := mongodb.NewConn(mongodbConfig)
	database := conn.DB
	zeroLogger := providers.ProvideLogger(loggerConfig, database)
	logger := mysql.NewLogger(zeroLogger)
	db := mysql.NewDB(mysqlConfig, logger)
	rbacUserRepository := repository.NewRbacUserRepository(db)
	rbacApiRepository := repository.NewRbacApiRepository(db)
	rbacRoleRepository := repository.NewRbacRoleRepository(db)
	rbacMenuRepository := repository.NewRbacMenuRepository(db)
	rbacRoleMenuRepository := repository.NewRbacRoleMenuRepository(db)
	rbacUserRoleRepository := repository.NewRbacUserRoleRepository(db)
	rbacMenuApiRepository := repository.NewRbacMenuApiRepository(db)
	adminAuthConfig := providers.NewAdminAuthConfig(configConfig)
	redisConfig := providers.NewRedisConfig(configConfig)
	client := redis.New(redisConfig)
	authService := service.NewAuthService(rbacUserRepository, rbacApiRepository, rbacRoleRepository, rbacMenuRepository, rbacRoleMenuRepository, rbacUserRoleRepository, rbacMenuApiRepository, adminAuthConfig, client)
	authController := controller.NewAuthController(requestRequest, authService, adminAuthConfig)
	rbacMenuService := service2.NewRbacMenuService(rbacMenuRepository, rbacMenuApiRepository, db)
	rbacMenuController := controller.NewRbacMenuController(requestRequest, rbacMenuService)
	rbacApiService := service2.NewRbacApiService(rbacApiRepository)
	rbacApiController := controller.NewRbacApiController(requestRequest, rbacApiService)
	rbacRoleService := service2.NewRbacRoleService(rbacRoleRepository, rbacRoleMenuRepository, db)
	rbacRoleController := controller.NewRbacRoleController(rbacRoleService, requestRequest)
	rbacUserService := service2.NewRbacUserService(db, rbacUserRepository, rbacUserRoleRepository)
	rbacUserController := controller.NewRbacUserController(requestRequest, rbacUserService)
	rbacStoreRepository := repository.NewRbacStoreRepository(db)
	rbacStoreService := service2.NewRbacStoreService(rbacStoreRepository)
	rbacStoreController := controller.NewRbacStoreController(requestRequest, rbacStoreService)
	uploadGroupRepository := repository.NewUploadGroupRepository(db)
	uploadGroupService := service2.NewUploadGroupService(uploadGroupRepository)
	uploadGroupController := controller.NewUploadGroupController(requestRequest, uploadGroupService)
	uploadFileRepository := repository.NewUploadFileRepository(db)
	settingRepository := repository.NewSettingRepository(db)
	settingDefaultRepository := repository.NewSettingDefaultRepository(db)
	settingService := service2.NewSettingService(settingRepository, settingDefaultRepository)
	uploadFileService := service2.NewUploadFileService(uploadFileRepository, settingService)
	uploadFileController := controller.NewUploadFileController(requestRequest, uploadFileService)
	userRepository := repository.NewUserRepository(db)
	userPointsLogRepository := repository.NewUserPointsLogRepository(db)
	userService := service2.NewUserService(db, userRepository, userPointsLogRepository)
	userController := controller.NewUserController(requestRequest, userService)
	settingController := controller.NewSettingController(requestRequest, settingService)
	settingDefaultService := service2.NewSettingDefaultService(settingDefaultRepository)
	settingDefaultController := controller.NewSettingDefaultController(requestRequest, settingDefaultService)
	articleCategoryRepository := repository.NewArticleCategoryRepository(db)
	articleCategoryService := service2.NewArticleCategoryService(articleCategoryRepository)
	articleCategoryController := controller.NewArticleCategoryController(requestRequest, articleCategoryService)
	articleRepository := repository.NewArticleRepository(db)
	articleService := service2.NewArticleService(articleRepository)
	articleController := controller.NewArticleController(requestRequest, articleService)
	regionRepository := repository.NewRegionRepository(db)
	regionService := service2.NewRegionService(regionRepository, settingService)
	regionController := controller.NewRegionController(regionService)
	healthController := controller.NewHealthController()
	controllers := &controller.Controllers{
		AuthController:            authController,
		RbacMenuController:        rbacMenuController,
		RbacApiController:         rbacApiController,
		RbacRoleController:        rbacRoleController,
		RbacUserController:        rbacUserController,
		RbacStoreController:       rbacStoreController,
		UploadGroupController:     uploadGroupController,
		UploadFileController:      uploadFileController,
		UserController:            userController,
		SettingController:         settingController,
		SettingDefaultController:  settingDefaultController,
		ArticleCategoryController: articleCategoryController,
		ArticleController:         articleController,
		RegionController:          regionController,
		HealthController:          healthController,
	}
	beforeMiddleware := middleware.NewBeforeMiddleware(zeroLogger)
	middlewares := &middleware.Middlewares{
		Before: beforeMiddleware,
	}
	authMiddleware := middleware2.NewAuthMiddleware(adminAuthConfig, authService)
	middlewareMiddlewares := &middleware2.Middlewares{
		Auth: authMiddleware,
	}
	corsConfig := providers.NewAdminCorsConfig(configConfig)
	engine := server.NewGin(controllers, middlewares, middlewareMiddlewares, corsConfig)
	httpServer := server.NewHTTPServer(serverConfig, engine, zeroLogger, db)
	return httpServer
}
