// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"zero-backend/internal/config"
	"zero-backend/internal/repository"
	"zero-backend/internal/service"
	"zero-backend/internal/storage/mongodb"
	"zero-backend/internal/storage/mysql"
	"zero-backend/modules/cli/command"
	"zero-backend/providers"
)

// Injectors from wire.go:

func wireRootCommand() *command.RootCommand {
	configConfig := config.New()
	conn := mongodb.NewConn(configConfig)
	database := conn.DB
	logger := providers.ProvideLogger(configConfig, database)
	mysqlLogger := mysql.NewLogger(logger)
	db := mysql.NewDB(configConfig, mysqlLogger)
	userRepository := repository.NewUserRepository(db)
	userPointsLogRepository := repository.NewUserPointsLogRepository(db)
	userService := service.NewUserService(db, userRepository, userPointsLogRepository)
	userListCommand := command.NewUserListCommand(userService)
	userCommand := command.NewUserCommand(userListCommand)
	migrateUpCommand := command.NewMigrateUpCommand(db)
	migrateCommand := command.NewMigrateCommand(migrateUpCommand)
	rootCommand := command.NewRootCommand(logger, userCommand, migrateCommand)
	return rootCommand
}
