// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"zero-backend/internal/config"
	"zero-backend/internal/storage/mongodb"
	"zero-backend/internal/storage/mysql"
	"zero-backend/modules/cli"
	"zero-backend/providers"
)

// Injectors from wire.go:

func wireCLIContext() *cli.Context {
	configConfig := config.New()
	conn := mongodb.NewConn(configConfig)
	database := conn.DB
	logger := providers.ProvideLogger(configConfig, database)
	mysqlLogger := mysql.NewLogger(logger)
	db := mysql.NewDB(configConfig, mysqlLogger)
	context := cli.NewContext(configConfig, logger, db)
	return context
}
