// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"zero-backend/internal/config"
	"zero-backend/internal/repository"
	"zero-backend/internal/service"
	"zero-backend/modules/cli/command"
	"zero-backend/modules/cli/runner"
	"zero-backend/pkg/locker"
	"zero-backend/pkg/mongodb"
	"zero-backend/pkg/mysql"
	"zero-backend/pkg/queue"
	"zero-backend/pkg/redis"
	"zero-backend/providers"
)

// Injectors from wire.go:

func wireApp() *command.RootCommand {
	configConfig := config.New()
	loggerConfig := configConfig.Logger
	mongodbConfig := providers.NewMongoDBConfig(configConfig)
	conn := mongodb.NewConn(mongodbConfig)
	database := conn.DB
	zeroLogger := providers.ProvideLogger(loggerConfig, database)
	redisConfig := providers.NewRedisConfig(configConfig)
	client := redis.New(redisConfig)
	redisLocker := locker.NewRedisLocker(client)
	mysqlConfig := providers.NewMySQLConfig(configConfig)
	logger := mysql.NewLogger(zeroLogger)
	db := mysql.NewDB(mysqlConfig, logger)
	userRepository := repository.NewUserRepository(db)
	userPointsLogRepository := repository.NewUserPointsLogRepository(db)
	userService := service.NewUserService(db, userRepository, userPointsLogRepository)
	userListCommand := command.NewUserListCommand(userService)
	userCommand := command.NewUserCommand(userListCommand)
	migrateCommand := command.NewMigrateCommand(db)
	queueManager := queue.NewQueueManager(client)
	queueCommand := command.NewQueueCommand(queueManager)
	rbacApiRepository := repository.NewRbacApiRepository(db)
	syncApiRunner := runner.NewSyncApiRunner(zeroLogger, rbacApiRepository)
	syncApiCommand := command.NewSyncApiCommand(syncApiRunner)
	rootCommand := command.NewRootCommand(zeroLogger, redisLocker, userCommand, migrateCommand, queueCommand, syncApiCommand)
	return rootCommand
}
